project_id = "iqzjdjgahymrciophhkg"

[functions.generate-caption]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.create-meme]
verify_jwt = false

[functions.get-meme-templates]
verify_jwt = false